### ISSUE TITLE
[Bug] Find an alternative for package-build-stats

### ISSUE THREAD

**Issue by jslim** [Jam3/adviser-plugin-dependencies#21]
Our adviser plugin is using package-build-stats library which is using node-sass@4.14.1

we need to invest time on this if there is an alternative way to replace package-build-stats

**Comment by n0wak** [comment]
This is an essential fix also because the existing version of **package-build-stats** fails to install on MacOS 12.3 on Mac Silicon.

**Comment by jslim** [comment]
Removing that package here https://github.com/Jam3/adviser-plugin-dependencies/pull/23
